openapi: 3.0.0
info:
  title: Sample API specification
  version: '1.0'
servers:
  - url: http://localhost:3000
paths:
  "/api/book/{book_id}":
    get:
      description: 本取得API
      operationId: getBook
      parameters:
        - name: book_id
          description: 本ID
          example: "1"
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: "1"
                  title:
                    type: string
                    example: "ぐりとぐら"
                required:
                  - id
                  - title
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Forbidden
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Not Found
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Server Error
        "503":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Service Unavailable
components:
  schemas:
    ErrorResponse:
      description: Error Schema
      type: object
      properties:
        message:
          type: string
          example: "Some Error"
    Book:
      description: 本
      type: object
      properties:
        id:
          description: 本ID
          type: string
          example: "1"
        title:
          description: 本のタイトル
          type: string
          example: "ぐりとぐら"
      required:
        - id
        - title

