openapi: 3.0.0
info:
  title: Sample API specification
  version: "1.0"
servers:
  - url: http://localhost:3000
paths:
  "/documents":
    get:
      description: ドキュメント一覧取得API
      operationId: getDocuments
      # クラスをカテゴライズして生成するために必要
      tags:
        - document
      parameters:
        - name: userId
          description: ユーザーID
          example: "1"
          in: query
          schema:
            type: string
          required: true
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Document"
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Forbidden
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Not Found
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Internal Server Error
        "503":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Service Unavailable
components:
  schemas:
    Document:
      description: ドキュメント
      type: object
      properties:
        id:
          description: ドキュメントID
          type: string
          example: "1"
        userId:
          description: ユーザーID
          type: string
          example: "1"
        sentence:
          description: 英文
          type: string
          example: "It's a sample sentence."
        translation:
          description: 訳
          type: string
          example: "これはサンプルの文章です。"
        createdAt:
          description: 作成日
          type: string
          example: "2023/1/1"
        updatedAt:
          description: 更新日
          type: string
          example: "2023/1/1"
        marks:
          type: array
          items:
            $ref: "#/components/schemas/Mark"
      required:
        - id
        - userId
        - sentence
        - translation
        - createdAt
        - updatedAt
        - marks
    Mark:
      description: 単語に付与されたマーク
      type: object
      properties:
        index:
          description: マークが付与されているインデックス
          type: integer
          example: 1
        type:
          description: マークの種別
          type: string
          example: "1"
      required:
        - index
        - type
    ErrorResponse:
      type: object
      properties:
        status:
          description: ステータスコード
          type: integer
          example: 400
        message:
          description: エラーメッセージ
          type: string
          example: "invalid parameters"
